name: Tweet

on:
  workflow_dispatch:
  schedule:
    - cron: "*/2 * * * *" # Runs Bot every 30 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Run Bot
        uses: dephraiim/twitter-bot-action@v1.2.1
        env:
          CONSUMER_TOKEN: ${{ secrets.CONSUMER_TOKEN }}
          CONSUMER_TOKEN_SECRET: ${{ secrets.CONSUMER_TOKEN_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
